# Data Preprocessing Tools (데이터 전처리 도구)

*   항목 추가
*   항목 추가



## Importing the libraries (라이브러리 import)


In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

## Importing the dataset (데이터세트 import)

In [ ]:
dataset = pd.read_csv('Data.csv') #데이터 set의 모든 값으로 데이터 프레임이 생성됨, 이 프레임을 dataset변수에 할당
x = dataset.iloc[:, :-1].values #특성(=독립변수) 행렬 x, iloc=추출하려는 열의 인덱스와 행의 인덱스를 받는 함수(행 부터 입력해야됨), :입력시 모든 범위에서 가져옴
y = dataset.iloc[:, -1].values #종속변수 행렬 y, -1은 마지막 인덱스 값이다.

In [ ]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data (유실 데이터 처리)

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean') #SimpleImputer 클래스의 인스턴스 생성 #첫인자는 채울부분을 명시(nan값), 2번째 인자는 무엇으로 대체할 것인지
imputer.fit(x[:, 1:3])#fit 메소드로 특성 행렬에 적용(x의 숫자가 있는 열에만 적용함), 1열과 2열만 적용 이때, python은 상한 값은 범위에 포함시키지 않으니까 3을 넣는것
x[:, 1:3] = imputer.transform(x[:, 1:3])  #누락된 정보를 평균 정보로 대체한 새로운 특성 행렬을 반환

In [ ]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data (범주형 데이터 처리)


### Encoding the Independent Variable (독립 변수 처리)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
#transformers의 인자 1.변환의 유형(인코딩) 2.인코딩에 사용할 클래스 이름 3.원핫 인코딩 변환을 적용할 열의 인덱스
#passthrough=>나머지 열을 변환하지 않음.
x = np.array(ct.fit_transform(x)) #특성 행렬에 연결

In [ ]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable (종속 변수 처리)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder() #하나의 벡터만 인코딩하므로 인자값 안넣어도 되는 경우
y = le.fit_transform(y) #이경우엔 numpy 배열 형태가 아니어도됨(머신러닝 모델에 사용할 때)

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set (테스트 세트, 훈련 세트 분리)

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size = 0.2, random_state = 1) #x,y 순서 지켜야됨
#3번째 인자= 분할비(권장: 훈련 80, 테스트 20), 무작위로 나뉘어짐, 4번째 인자=동일한 훈련세트, 테스트 세트가 나오도록 고정

In [ ]:
print(x_train) #훈련 세트의 특성행렬

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(x_test) #테스트 세트의 특성행렬

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_train) #훈련 세트의 종속변수

[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test) #테스트 세트의 종속변수

[0 1]


## Feature Scaling (특성 스케일링)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler() #자동으로 작동하므로 매개변수 필요x
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:]) #3:는 3부터 시작해 모든 열을 가져온다.
#fit과 transform의 차이점?
#fit 메서드를 사용해 평균을 구하고 표준편차를 구한다.
#transform 메서드를 사용해 변경된 값을 적용한다.(식을 적용한다)
x_test[:, 3:] = sc.transform(x_test[:, 3:])
#test데이터는 배포 후에 관측하는 새로운 데이터니까 transform만 적용
#위에서 fit한 scaler를 그대로 사용해야 하기 때문에 다시 fit을 할경우 별도의 scaler가 되어버린다.(이는 아직 갖지 않은 데이터라 모순임)

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

df = pd.read_csv('Data3.csv', delimiter=';')


x = df.drop('quality', axis=1)
y = df['quality']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

sc = StandardScaler()

x_train = sc.fit_transform(x_train)

x_test = sc.transform(x_test)

print(x_train)
print(x_test)

In [ ]:
print(x_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
